### ISSUE TITLE
USB microphone is not working

### ISSUE THREAD

**Issue by bgyu** [techmakerai/ChatGPT-4o-Powered-Voice-Assistant-with-Python#1]
Hi, I tried this python app, but for some reason the app can't receive any microphone input. I tried my USB microphone with other applications, it works without any issue. Any idea how to resolve this issue?

**Comment by bgyu** [comment]
Never mind, I checked the source code. I have to start with "Jack".

**Comment by bgyu** [comment]
Problem resolved.

**Comment by techmakerai** [comment]
Glad you figured it out. Yes, you will need to start with a wake word which you can change too.
